### PR TITLE
Transducers

### PR DESCRIPTION
**Pull request by mahinshaw**
Relates to Issue #30. I added transducers namespace, and a test file.  I did not however re-implement except-first macro.  I was not really sure how to do this (still fairly new to clojure).  Any ideas would be appreciated!  All the input functions are now transducers.  I pulled your doc comments from core, and modified them for the transducer versions.  I copied over the helpers for casting as well, because i figured that may decrease requiring core when it's not wanted.  Let me know what you think.  I will be happy to make any necessary changes you think are needed.  I Learned a lot doing this.

Also, I added a structify function to separate the functionality out.  I can change it to just being a mappify function if you would rather it be that way.

### CODE REVIEW

**Comment by metasoarous** [comment]
Awesome! Thanks so much for working on this!

I've been pretty busy, so it might be a minute before I get a chance to look at this. I'm keen to see what you've done though.

Thanks again. Back to you soon.

**Comment by metasoarous** [comment]
@mahinshaw - A few thing to note so far:

* I think using `(into [] xf coll)` is a bit more idiomatic than `(transduce xf conj [] coll)`in the examples, so I went ahead and changed that over (see my new transducers branch).
* I'm generally warm to the idea of having a separate namespace with all the same function names. However, it would be good to remove duplicate function definitions wherever possible; one namespace could just alias the definitions of another.
* We could also clean up a lot of code by having the core API use the transducer function definitions. This might involve some namespace shuffling to get the dependencies all working right, but would be worth it (I can add more details about what I'm thinking if you like).

Those are my thoughts so far. I'll add more as I'm able to actually dig into the code. Feel free to keep hacking on any of these notes, and thanks again!

**Comment by metasoarous** [comment]
Oh; and we'll need to get docstrings updated to reflect the fact that they're transducers. I think most of them are the same at the moment.

Thanks again!

**Comment by mahinshaw** [comment]
If we are going to leverage the transducers for for the implementations in core, would it make sense to add new arities (ala map, filter, etc)?  In that case, there would only be one namespace.  If not, I can work towards having core reference the transducers namespace, and use the transducers for the implementations within core.  Likewise, the helper functions in core will be aliases of the helpers in transducers, as to avoid circular references.

I can get started on cleaning up the doctstrings first.  I will also start work on using the transducers to implement the core methods.  Thanks for the feedback.

**Comment by metasoarous** [comment]
I've thought about dispatching behavior on arity, but the problem with that is that we're already using arity dispatching to make the options map optional in these functions. So we wouldn't be able to do it _solely_ with arity dispatch. For the 1-arity case, we'd have to check the type of the argument; if map, return a transducer with options hash; otherwise, treat as a collection and process normally. Part of the reason I've been slacking on this issue is that I've been uncertain which approach here (the one just described or the separate namespace) is the cleanest from an API perspective. At the moment I'm leaning towards a single API, but I'll get back to you (and you're thoughts are welcome).

This may be obvious already, but to implement the core methods using the tranducers we can just do `(defn mappify [opts coll] (sequence (trans/mappify opts) coll))`. I thought about using `eduction` instead of `sequence`, but this has a couple of gotchas (it doesn't cache results like a true `seq` would). It's still worth considering because it would be more naturally operable with other tranducer stuff, but I think if folks want that they can just use the transducer version and apply eduction themselves. Not _too_ concerned with this particular detail.

I think it might be nice to do a major version bump for the release so that folks can continue to use the library as it currently stands for non-1.7 projects. Though, it would be cool if we could use reader conditionals or something so that the tranducer versions would only be supported if you're running >1.7. Not sure if this is possible; something else to look into.

**Comment by mahinshaw** [comment]
The issue with arity dispatching crossed my mind.  Would it make sense to force arity 0 and 1 to always return the transducer.  Then arity 2 will take the collection. For example:

```clojure
(defn mappify
  ([] (mappify {}))
  ([opts] (mappify-xform opts))
  ([opts coll] (sequence (mappify-xform opts) coll))
```

While this would force some boilerplate on the user for cases where they want to do ```(mappify coll)```, simplifying the api may be more beneficial.

I will look into reader conditionals today as well.  I agree that using these would be really nice with regards to adding version specific implementations.  However, I do wonder if that could make future changes/maintenance more cumbersome. At the moment, I don't see it as a big issue though.

**Comment by metasoarous** [comment]
Having 1 arity always return a transducer would be a breaking API change, and I'd rather avoid that if we can. Still waffling on same namespace...

I just realized reader conditionals for versions doesn't make sense, since it's a 1.7 feature (duh...). Could just put the entire contents of a trandsucer namespace in a try/catch clause, but that's sort of warty. It would also preclude using the transducer functions to implement the vanilla collection processing functions, which is a pitty. And I've been thinking it would be great to add cljs support as well, and that would be greatly aided by having reader conditionals in 1.7. Also, we're not in python here; adoption of 1.7 seems to be pretty strong. So I'm thinking major (would minor be ok?) version bump, and require 1.7.

**Comment by mahinshaw** [comment]
Minor version bump should be okay, as long as the README states that minor versions might include breaking changes.

Just to sum up what I understand as the current conflict:

* A single namespace is the most desirable goal.  To do that, we need to integrate the transducers such that arity 1 checks to see if the param is a map or a collection, and dispatches from there.
    * Pros: Cleaner API
    * Cons: Arity 1 has overloaded functionality.  May be confusing.

* Seperate namespaces - This aleviates the issue with arity overloading.  Implementation of the core functions would leverage the transducers via ```(sequence ...)```.
    * Pros: no issues with arity overloading in core functions.
    * Cons: a more cumbersome API.

It may be worth exploring the single namespace approach as noted above.  It really would be nice to have a single API.

Regarding Clojurescript - From what I understand, the only platform differences would be the csv parsers, and the io.  Is that correct?

**Comment by mahinshaw** [comment]
I updated core to use the transducers.  I will work on updating the doc strings in the transducers namespace next.

**Comment by mahinshaw** [comment]
@metasoarous - Are you interested in me doing this with the transducers integrated into the core namespace, and implementing the arity 1 overload, as discussed earlier?

**Comment by metasoarous** [comment]
Hi @mahinshaw 

Sorry for the radio silence; I've been swamped lately, but should have more time to look at this in a couple of weeks.

I guess my fundamental objection to doing the arity-1 overload is that, Clojure being a dynamic language, thinking about argument types too much feels a bit non-idiomatic. A particular case in point: it's totally within reason to have a map of k,v pairs and want to write them to rows of a CSV file with two columns (k,v). Checking `map?` to dispatch behaviour means you'd have to call `(seq the-map)` to achieve the desired behaviour. Obviously this isn't a huge deal, but it does smell a little because you're having to think about the types of things, not just how they behave.

Still, mocking the arity dispatch of core functions like map, filter, take, etc, is awfully tempting. I'm tempted to throw out a quick survey to the Clojure mailing list to see what people think about these two options. I've gotten great feedback doing this with other projects.

I think for now though, let's stick with separate namespaces. That is the least obtrusive path.

A few quick notes about how I think things should be set up (for now, anyway): I don't think we should treat the transducer namespace as the complete set of implementations. And right now there is a lot of duplication of helper functions (like the parsing functions). Anything that is not explicitly working with transducers any differently than directly with collections (such as `spit-csv`) should be in some sort of `impl` namespace, and then get aliased into the two APIs separately (such that docstrings are preserved; maybe add a helper function for this...). Also, we should consider whether there is some more "transducer-friendly" way to do things like `spit-csv`.

Some other concerns: it might be nice to shore up some of the other features I've had in mind before we merge in your work and cut a new release. My thinking there is that it would be nice if folks who are stuck with Clojure < 1.7 were able to use those features on some 0.x release, and let all the new transducer stuff fall into the > 1.x semantic-csv versions (I'd also like to take advantage of reader conditionals to make the library cljs compatible, requiring Clojure 1.7). Hopefully I'll be able to take care of some of those main things in a couple of weeks here when time opens up for me a bit. Would you be at all interested in helping with that stuff as well?

Once again; thanks so much for you work on this :-)

**Comment by mahinshaw** [comment]
@metasoarous - Sounds like great ideas.  I agree with regards to arity overloading.  It feel a little awkward, but I am happy to work with a consensus.

I will work on pulling out the duplicates into a separate namespace.  Regarding the non transducer functions - which I believe are just ```spit-csv```, ```slurp-csv```, and ```batch``` - how do we want to handle avoiding circular references?  If they are in an ```impl``` namespace, we would need to import either ```core``` or ```transducers``` for the implementation, and then reference ```impl``` in the namespace that we alias the function in.  Does that make sense, or am I missing something?  There is definitely no problem with moving ```batch``` and the ```->{int,long,float,double}``` into ```impl``` and then aliasing them in core/transducers namespaces.

You mentioned doing spit-csv in a "tranducer friendly" way.  I am curious as to what you are thinking here.  One thing I do notice about the implementation, is that we do a batch call, which loads everything into an sequence of batches.  I imagine its possible to do this batching in a transducer along with the ```vectorize``` transducer, which might be nice.  Thoughts?

I will get to work on those details soon.  Anything else that come to mind let me know, I am more than happy to help with anything I can.

**Comment by metasoarous** [comment]
You're absolutely right about circular dependencies.

The "transducer friendly" idea: functions like `sequence`, `into` and `transduce` take transducers as arguments. The `transduce` function in particular is evocative in that it's like reduce, and builds up some "thing" based on a collection. This is analogous to `spit-csv`, if one considers the "thing" being built up to be a file. So perhaps there's something along these lines we could do here, decomposing `spit-csv` as it currently stands into the part that is doing all the transformation and that part doing the reduction. Then the `core` namespace could use these functions and everything would feel pretty happy to me. That seems to fall in line with what you were thinking with `batch` and `vectorize`, as well.

If you're keen to help out on other things, I'd greatly appreciate that. The issues that come to mind are #26 and #2 (and maybe even 29, though I'm not convinced that one is a good idea...). #26 in particular is a good place to start, since I think it's fairly simple, and has been specifically asked for by some users. #2 is a bit more involved, and I've got some thoughts and code moving along already, but if you're interested in working on that as well, we could hit the gitter chat to discuss further.

**Comment by mahinshaw** [comment]
Ok, that makes sense to use ```transduce``` with a ```spit-csv``` tranducer.  I thought that might be what you were thinking.  I will look in to that.  I am probably going to start by making a ```batch``` transducer, and mover from there.

I tell you what, I will get started on a PR for #2 so that it can get integrated into the 0.x branch.

I can get started on #26 as well.  I think it may be best to do the original for the 0.x branch as well, and then migrate that to transducers afterwords.

Once #2 and #26 are at a stable point, I will get back to updating the transducers implementation.

You mentioned gitter.  I am happy to get on there if I am available.  I am also on the [clojurians slack](http://clojurians.net) channel, so you can ping me there (mahinshaw).

**Comment by metasoarous** [comment]
Re `transduce` and `spit-csv`; that's _almost_ what I was thinking. Instead of passing a `spit-csv` transducer to `transduce`, however, I was thinking we'd have a function that would behave like the `transduce` part of the setup you describe. You would specifically take a filename or handle and a processing transducer and write to a file. But most of the old logic of what is now `spit-csv` would still fit nicely in the context of a function that returns a transducer, which could then be passed to the other `transduce`-like function, which does the actual writing. Does that seem reasonable?

**Comment by mahinshaw** [comment]
@metasoarous I got this branch up to date with the transform header change.  Is this something you are planning on merging.  It's been here for quite a while, and I have actually pulled this out to use in a couple of projects for work.  It would be nice to leverage it all as a lib, rather than copy pasting.  If there is anything you would like me to clean up, or work on, I am happy to do that.  Also, the sniffer might be nice to get in, but it's not essential.

**Comment by metasoarous** [comment]
Hey @mahinshaw. Yes! I do want to merge this. Sorry that I still haven't gotten around to it. I wanted to review some of the more intricate transducer code, but I haven't done any transducer implementation yet, so it's just been on the backburner for me. I'm hoping to have some time for this in the next few weeks, but will try to get this ironed out by the end of the year at the latest.

Thanks again!

**Comment by mahinshaw** [comment]
If it make you feel better, I basically took the transducer code for `map`, and made it work for this use case.  Implementing transducers is actually what made them finally make sense to me (and helped a lot with ring and boot tasks).

Thanks again, and if I can be of any help, or you need my code cleaned/altered, please let me know.

**Comment by metasoarous** [comment]
Hah! That does help :-)

The one thing I vaguely remember was that there was a function using volatiles where I wasn't sure it was needed. Would you mind looking to see if you can find something like that?

**Comment by mahinshaw** [comment]
I looked into the use of `volatile!` in the transducers ns.  The ones that are there are fairly essential. `volatile!` is the canonical way to manage state within a transducer (at least from what I have seen in clojure.core), and that is what I have been using them for.  Furthermore, I am using them for managing stateful things like getting/setting the header, and then there is one case in vectorize that we want to prepend the header. The trick is really that the inner `fn` needs to access state outside of itself since it is called for every processing step.  Honestly, it would be great if there were a better way to do what I did, but I couldn't come up with anything.  Again, suggestions are most welcome.

**Comment by metasoarous** [comment]
Hey @mahinshaw! Agreed; `volatile!` is certainly the right way to manage state in a transducer. I guess the main point was that I vaguely remember there being a transducer that was using state where I thought there might be a way to solve the problem purely. Was a while ago so I don't remember the details.

Looks like our transducers branches diverged somehow... would you mind merging those and updating the PR? Once those are on the same page, I can review.

For the record, I've decided on sticking with separate namespaces for the transducers. Once things look sane, we can put together an alpha release. I'd like to get cljc operability set up before we finalize the 1.0.0 release, and in general give a chance for interested parties to comment.

**Comment by mahinshaw** [comment]
@metasoarous I was originally targetting master as the branch to merge into.  Is there a reason to merge into your transducer branch?  I don't mind, I'm just curious.  Also, my guess about the divergence is because I rebased on master because of the changes around transform header.

**Comment by metasoarous** [comment]
I'd just like to be able to work on it in a separate branch until I'm ready to merge it in. Also, I don't think I ever released a version with the transform-header work (#26), and I'd like to keep master where it is until I do that.

Ah... I see about the rebase... You know what; Let me just trash that branch and merge it into a new one.

**Comment by metasoarous** [comment]
The one thing I did in my branch was change the `(transduce ...)` examples to `(into [] ...)`, which is more idiomatic. If you wouldn't mind doing that on your fork, I'd appreciate it.

**Comment by metasoarous** [comment]
Woops... didn't mean to kill the PR...

**Comment by metasoarous** [comment]
I'll take a deeper look soon.

**Comment by mahinshaw** [comment]
I saw your comment about using `into` instead of `transduce`.  I went over those the comments, and there aren't any more usages of `transduce`. I actually think I did that a while back.

**Comment by metasoarous** [comment]
Oh; ok. Thanks. Still aiming for end of year :-)

**Pull request merged**
