### PR TITLE
Robust cast fns

### PR DESCRIPTION
**Pull request by sbelak**
Made built in cast fns more robust (as per #36) and added ->boolean.

### CODE REVIEW

**Comment by sbelak** [comment]
p.s. ff you don't care for the def+partial style, I'm happy to rewrite that part.

**Comment by metasoarous** [comment]
Looks good; I'm fine with `(def _  (partial ...))`. My only criticism is that it does produce `:argslist` metadata, which I rather like for ease of use at the REPL and IDE/editor. (I know these are simple functions, but still...) So if you leave it, please either add the argslist metadata manually, or do a macro, as you like.

Thanks!

**Comment by sbelak** [comment]
Changed to regular functions. 

Tried using macros but it just looks strange as it doesn't coincide with any existing macro pattern (the problem is having a docstring and then just solitary functions/params, rather than a body or expression as expected).

**Comment by metasoarous** [comment]
OK; Sounds good. Thanks. Will merge tonight hopefully.

**Comment by metasoarous** [comment]
@sbelak Sorry for the delay on this; 24 days ago... Sheesh. We just moved, so things have been crazy. Still, sorry for not taking the time to "push a button" after all your work. Your contribution is very much appreciated :-)

**Pull request merged**
