### PR TITLE
Lazy batch

### PR DESCRIPTION
**Pull request by sbelak**

### CODE REVIEW

**Comment by metasoarous** [comment]
Can you explain to me why the batching isn't lazy currently?

**Comment by sbelak** [comment]
Thinking through it again, I was wrong, it already is. I thought that cast-with retains head in the last line, but it doesn't because ->> of course turns the code "inside out". Sorry for wasting your time. What could be done though is do all the processing for each batch in a pmap.

**Comment by metasoarous** [comment]
No worries.

It would be awesome parallelize/pipeline things, but I would also like to rewrite this library in cljc on the next major increment, so I don't want pmap hard-coded. And since we're doing transducers for the rewrite anyway, this would give us some nice avenues for describing the computational flow abstractly while leaving the execution details as a separate concern. So it should be really straight forward to take the transducer versions of the API to pipeline the data.

**Comment by metasoarous** [comment]
I'm closing this, since the initial issue is a non-issue. However, if you'd like to open up an issue for running things in parallel please do. Just keep in mind that we'll soon have the transducers code for doing parallelization with pipeline very soon. So decide whether that's enough, or whether any of the current api could benefit from an `:parallelism` option (or some such).

**Pull request closed without merging**
